import type { Metadata } from "next";
import { BBH_Sans_Bartle, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
});

const bartle = BBH_Sans_Bartle({
    variable: "--font-bartle",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${roboto.variable} ${bartle.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
